### PR TITLE
Indent your code por favor

### PR DESCRIPTION
**Pull request by edgecoder**
We found plenty of not needed spaces in there, and also your code was completely lacking of proper indentation. This commit will fix this for you, if you chose to accept it.

### CODE REVIEW

**Comment by BlackGuyCoding** [comment]
Great!

**Comment by BlackGuyCoding** [comment]
+1

**Comment by jcbarragan** [comment]
Fantastic!

**Comment by moltenglacier** [comment]
+1

**Comment by troyswood** [comment]
Nice job @edgecoder!

**Comment by mikesankovich** [comment]
Nice work. Keep it up!!! :+1:

**Pull request merged**
